version: '3'
services:
    app:
        container_name: recipe-app
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /opt/app
        ports:
            - "5001:5001"
    mongo:
        container_name: recipe-mongo
        image: mongo:latest
        volumes:
            - ./data/mongoDB:/data/db
        ports:
            - '27017:27017'
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        #     - MONGO_INITDB_ROOT_PASSWORD=bdung
